### ISSUE TITLE
Getting constatly Warning: getDefaultProps

### ISSUE THREAD

**Issue by vkampouris** [joshwnj/react-visibility-sensor#134] opened 2018-09-24 15:35 UTC
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

What should i do in this case?

**Comment by joshwnj** [comment] 2018-10-11 16:18
@vkampouris this should be fixed in v5.0.1, now that #123 is merged.

Please re-open if the issue is still occurring.

**Closed by joshwnj** 2018-10-11 16:18 UTC
