### ISSUE TITLE
onChange not firing in latest versions

### ISSUE THREAD

**Issue by kroney** [joshwnj/react-visibility-sensor#129] opened 2018-09-11 07:03 UTC
Hey
I tried to add the VisibilitySensor to my component but found out that in the latest version the onChange event is not firing.
In Version 3.11.1 it still works fine.
Were there any changes to the API that are not yet documented, or is this a bug?

**Comment by Templaris** [comment] 2018-09-11 07:05
I am confirming this bug in my project. I had to force to use version 3.11. Later contains bug described above.

**Comment by ericf89** [comment] 2018-09-11 11:32
Seems to stick when devtools are open, not sure if that's a feature or not. :D

**Comment by joshwnj** [comment] 2018-09-11 13:17
@kroney @Templaris thanks for reporting. Can you please confirm the version where the bug was seen? Also the version of react being used?

Also, if you take a look at this example, are you able to modify it in some way that reproduces the bug? https://codesandbox.io/s/p73kyx9zpm

**Comment by ericf89** [comment] 2018-09-14 18:48
Hmm.  I tried to repo and couldn't. Might have just been due to my initial misunderstanding of how the sensor worked. I didn't realize it actually needed to wrap something for things to update appropriately.

**Comment by joshwnj** [comment] 2018-09-17 09:05
Cool, thanks - I'll close this for now but we can reopen if we get a reproducible case.

**Closed by joshwnj** 2018-09-17 09:05 UTC
